import { expect, test } from 'vitest';
import { allSpecs } from '../src/modules/registry';

const EXPECTED = [
  'ad',
  'adsr',
  'arp',
  'atn',
  'bern',
  'burst',
  'chaos',
  'chords',
  'chorus',
  'clock',
  'clockdiv',
  'cloud',
  'comb',
  'comp',
  'compare',
  'crush',
  'cvrec',
  'ddelay',
  'diode',
  'dist',
  'divmult',
  'djfilt',
  'drum2',
  'dualbp',
  'duo',
  'envfilt',
  'euklid',
  'fixedbank',
  'flanger',
  'fmop',
  'fmvoice',
  'formant',
  'freeze',
  'freqshift',
  'func',
  'fuzz',
  'gate',
  'gdelay',
  'glitch',
  'grain',
  'hats',
  'kbd',
  'kick',
  'ladder',
  'lfo',
  'lofi',
  'logic',
  'lpg',
  'matrix',
  'mix',
  'mix8',
  'monov',
  'morph',
  'ms20',
  'mult',
  'noise',
  'noiselab',
  'out',
  'overdrive',
  'phaser',
  'pitch',
  'pluck',
  'polivoks',
  'quad',
  'quant',
  'rectify',
  'reson',
  'reverb',
  'ring',
  'rndwalk',
  'rvsdelay',
  'sampler',
  'saturate',
  'scope',
  'sdelay',
  'seq',
  'seq16',
  'shift',
  'shimmer',
  'slew',
  'slicer',
  'snh',
  'spread',
  'sswitch',
  'steiner',
  'super',
  'svf',
  'tape',
  'trem',
  'trigseq',
  'tube',
  'turing',
  'vca',
  'vco',
  'voct',
  'volt',
  'wasp',
  'wavefold',
  'wavetable',
  'xfade',
] as const;

test('catalog is exactly the 100 planned modules', () => {
  expect(EXPECTED).toHaveLength(100);
  expect(new Set(allSpecs().map((s) => s.def.id))).toEqual(new Set(EXPECTED));
});

test('every worklet module has a registered processor name and every native has a native spec', () => {
  for (const s of allSpecs()) {
    if (s.def.worklet) expect(s.def.worklet.length).toBeGreaterThan(0);
    else expect(s.native).toBeDefined();
  }
});
