import type { ModuleDef } from '../../core/types';

export const def: ModuleDef = {
  id: 'ddelay',
  name: 'DELAY',
  sub: 'DIGITAL · SYNC',
  hp: 10,
  cat: 'FX',
  worklet: 'ddelay',
  knobs: [
    {
      id: 'time',
      label: 'TIME',
      min: 0.02,
      max: 3,
      initial: 0.375,
      fmt: 'fMs',
      curve: 'log',
      big: true,
      cvIn: 'tcv',
    },
    { id: 'fb', label: 'FEEDBK', min: 0, max: 0.98, initial: 0.35, fmt: 'fPc', cvIn: 'fcv' },
    {
      id: 'tone',
      label: 'TONE',
      min: 400,
      max: 16000,
      initial: 4000,
      fmt: 'fHz',
      curve: 'log',
      cvIn: 'tocv',
    },
    { id: 'mix', label: 'MIX', min: 0, max: 1, initial: 0.35, fmt: 'fPc', cvIn: 'mcv' },
    { id: 'tcvA', label: 'TIME CV', min: -1, max: 1, initial: 0, fmt: 'f1', attenuates: 'tcv' },
    { id: 'fcvA', label: 'FB CV', min: -1, max: 1, initial: 0, fmt: 'f1', attenuates: 'fcv' },
    { id: 'tocvA', label: 'TONE CV', min: -1, max: 1, initial: 0, fmt: 'f1', attenuates: 'tocv' },
    { id: 'mcvA', label: 'MIX CV', min: -1, max: 1, initial: 0, fmt: 'f1', attenuates: 'mcv' },
  ],
  sws: [
    {
      id: 'sync',
      label: 'SYNC',
      options: ['FREE', '1/1', '1/2', '1/4.', '1/4', '1/8.', '1/8', '1/8T', '1/16', '1/16T'],
    },
  ],
  ins: [
    { id: 'in', label: 'IN', kind: 'a' },
    { id: 'tcv', label: 'TIME CV', kind: 'c' },
    { id: 'fcv', label: 'FB CV', kind: 'c' },
    { id: 'tocv', label: 'TONE CV', kind: 'c' },
    { id: 'mcv', label: 'MIX CV', kind: 'c' },
    { id: 'clk', label: 'CLOCK', kind: 'g' },
  ],
  outs: [{ id: 'out', label: 'OUT', kind: 'a' }],
  leds: ['clk'],
};
